// Code generated by protoc-gen-grpc-federation. DO NOT EDIT!
// versions:
//
//	protoc-gen-grpc-federation: (devel)
//
// source: federation/other.proto
package federation

import (
	"context"
	"io"
	"log/slog"
	"reflect"
	"time"

	grpcfed "github.com/mercari/grpc-federation/grpc/federation"
	grpcfedcel "github.com/mercari/grpc-federation/grpc/federation/cel"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"

	favorite "example/favorite"
)

var (
	_ = reflect.Invalid // to avoid "imported and not used error"
)

// Federation_GetResponseVariable represents variable definitions in "federation.GetResponse".
type OtherService_Federation_GetResponseVariable struct {
	P *Post
}

// Federation_GetResponseArgument is argument for "federation.GetResponse" message.
type OtherService_Federation_GetResponseArgument struct {
	Id string
	OtherService_Federation_GetResponseVariable
}

// Federation_GetResponse_PostArgument is custom resolver's argument for "post" field of "federation.GetResponse" message.
type OtherService_Federation_GetResponse_PostArgument struct {
	*OtherService_Federation_GetResponseArgument
}

// Federation_PostVariable represents variable definitions in "federation.Post".
type OtherService_Federation_PostVariable struct {
	Cmp           bool
	FavoriteValue favorite.FavoriteType
	Reaction      *Reaction
	U             *User
}

// Federation_PostArgument is argument for "federation.Post" message.
type OtherService_Federation_PostArgument struct {
	OtherService_Federation_PostVariable
}

// Federation_ReactionVariable represents variable definitions in "federation.Reaction".
type OtherService_Federation_ReactionVariable struct {
	Cmp bool
}

// Federation_ReactionArgument is argument for "federation.Reaction" message.
type OtherService_Federation_ReactionArgument struct {
	V favorite.FavoriteType
	OtherService_Federation_ReactionVariable
}

// Federation_UserVariable represents variable definitions in "federation.User".
type OtherService_Federation_UserVariable struct {
}

// Federation_UserArgument is argument for "federation.User" message.
type OtherService_Federation_UserArgument struct {
	Id   string
	Name string
	OtherService_Federation_UserVariable
}

// OtherServiceConfig configuration required to initialize the service that use GRPC Federation.
type OtherServiceConfig struct {
	// Resolver provides an interface to directly implement message resolver and field resolver not defined in Protocol Buffers.
	// If this interface is not provided, an error is returned during initialization.
	Resolver OtherServiceResolver // required
	// ErrorHandler Federation Service often needs to convert errors received from downstream services.
	// If an error occurs during method execution in the Federation Service, this error handler is called and the returned error is treated as a final error.
	ErrorHandler grpcfed.ErrorHandler
	// Logger sets the logger used to output Debug/Info/Error information.
	Logger *slog.Logger
}

// OtherServiceClientFactory provides a factory that creates the gRPC Client needed to invoke methods of the gRPC Service on which the Federation Service depends.
type OtherServiceClientFactory interface {
}

// OtherServiceClientConfig helper to create gRPC client.
// Hints for creating a gRPC Client.
type OtherServiceClientConfig struct {
	// Service FQDN ( `<package-name>.<service-name>` ) of the service on Protocol Buffers.
	Service string
}

// OtherServiceDependentClientSet has a gRPC client for all services on which the federation service depends.
// This is provided as an argument when implementing the custom resolver.
type OtherServiceDependentClientSet struct {
}

// OtherServiceResolver provides an interface to directly implement message resolver and field resolver not defined in Protocol Buffers.
type OtherServiceResolver interface {
	// Resolve_Federation_GetResponse_Post implements resolver for "federation.GetResponse.post".
	Resolve_Federation_GetResponse_Post(context.Context, *OtherService_Federation_GetResponse_PostArgument) (*Post, error)
}

// OtherServiceCELPluginWasmConfig type alias for grpcfedcel.WasmConfig.
type OtherServiceCELPluginWasmConfig = grpcfedcel.WasmConfig

// OtherServiceCELPluginConfig hints for loading a WebAssembly based plugin.
type OtherServiceCELPluginConfig struct {
	CacheDir        string
	RefreshDuration time.Duration
}

// OtherServiceUnimplementedResolver a structure implemented to satisfy the Resolver interface.
// An Unimplemented error is always returned.
// This is intended for use when there are many Resolver interfaces that do not need to be implemented,
// by embedding them in a resolver structure that you have created.
type OtherServiceUnimplementedResolver struct{}

// Resolve_Federation_GetResponse_Post resolve "federation.GetResponse.post".
// This method always returns Unimplemented error.
func (OtherServiceUnimplementedResolver) Resolve_Federation_GetResponse_Post(context.Context, *OtherService_Federation_GetResponse_PostArgument) (ret *Post, e error) {
	e = grpcfed.GRPCErrorf(grpcfed.UnimplementedCode, "method Resolve_Federation_GetResponse_Post not implemented")
	return
}

// OtherService represents Federation Service.
type OtherService struct {
	UnimplementedOtherServiceServer
	cfg           OtherServiceConfig
	logger        *slog.Logger
	errorHandler  grpcfed.ErrorHandler
	celCacheMap   *grpcfed.CELCacheMap
	tracer        trace.Tracer
	resolver      OtherServiceResolver
	celTypeHelper *grpcfed.CELTypeHelper
	celEnvOpts    []grpcfed.CELEnvOption
	celPlugins    []*grpcfedcel.CELPlugin
	client        *OtherServiceDependentClientSet
}

// NewOtherService creates OtherService instance by OtherServiceConfig.
func NewOtherService(cfg OtherServiceConfig) (*OtherService, error) {
	if cfg.Resolver == nil {
		return nil, grpcfed.ErrResolverConfig
	}
	logger := cfg.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(io.Discard, nil))
	}
	errorHandler := cfg.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(ctx context.Context, methodName string, err error) error { return err }
	}
	celTypeHelperFieldMap := grpcfed.CELTypeHelperFieldMap{
		"grpc.federation.private.federation.GetResponseArgument": {
			"id": grpcfed.NewCELFieldType(grpcfed.CELStringType, "Id"),
		},
		"grpc.federation.private.federation.PostArgument": {},
		"grpc.federation.private.federation.ReactionArgument": {
			"v": grpcfed.NewCELFieldType(grpcfed.CELIntType, "V"),
		},
		"grpc.federation.private.federation.UserArgument": {
			"id":   grpcfed.NewCELFieldType(grpcfed.CELStringType, "Id"),
			"name": grpcfed.NewCELFieldType(grpcfed.CELStringType, "Name"),
		},
	}
	celTypeHelper := grpcfed.NewCELTypeHelper("federation", celTypeHelperFieldMap)
	var celEnvOpts []grpcfed.CELEnvOption
	celEnvOpts = append(celEnvOpts, grpcfed.NewDefaultEnvOptions(celTypeHelper)...)
	celEnvOpts = append(celEnvOpts, grpcfed.EnumAccessorOptions("favorite.FavoriteType", favorite.FavoriteType_value, favorite.FavoriteType_name)...)
	celEnvOpts = append(celEnvOpts, grpcfed.EnumAccessorOptions("federation.MyFavoriteType", MyFavoriteType_value, MyFavoriteType_name)...)
	svc := &OtherService{
		cfg:           cfg,
		logger:        logger,
		errorHandler:  errorHandler,
		celEnvOpts:    celEnvOpts,
		celTypeHelper: celTypeHelper,
		celCacheMap:   grpcfed.NewCELCacheMap(),
		tracer:        otel.Tracer("federation.OtherService"),
		resolver:      cfg.Resolver,
		client:        &OtherServiceDependentClientSet{},
	}
	if resolver, ok := cfg.Resolver.(grpcfed.CustomResolverInitializer); ok {
		ctx := context.Background()
		if err := resolver.Init(ctx); err != nil {
			return nil, err
		}
	}
	return svc, nil
}

// CleanupOtherService cleanup all resources to prevent goroutine leaks.
func CleanupOtherService(ctx context.Context, svc *OtherService) {
	svc.cleanup(ctx)
}

func (s *OtherService) cleanup(ctx context.Context) {
	for _, plugin := range s.celPlugins {
		plugin.Close()
	}
}

// Get implements "federation.OtherService/Get" method.
func (s *OtherService) Get(ctx context.Context, req *GetRequest) (res *GetResponse, e error) {
	ctx, span := s.tracer.Start(ctx, "federation.OtherService/Get")
	defer span.End()
	ctx = grpcfed.WithLogger(ctx, s.logger)
	ctx = grpcfed.WithCELCacheMap(ctx, s.celCacheMap)
	defer func() {
		if r := recover(); r != nil {
			e = grpcfed.RecoverError(r, grpcfed.StackTrace())
			grpcfed.OutputErrorLog(ctx, e)
		}
	}()
	defer func() {
		for _, celPlugin := range s.celPlugins {
			celPlugin.Cleanup()
		}
	}()
	res, err := s.resolve_Federation_GetResponse(ctx, &OtherService_Federation_GetResponseArgument{
		Id: req.GetId(),
	})
	if err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		grpcfed.OutputErrorLog(ctx, err)
		return nil, err
	}
	return res, nil
}

// resolve_Federation_GetResponse resolve "federation.GetResponse" message.
func (s *OtherService) resolve_Federation_GetResponse(ctx context.Context, req *OtherService_Federation_GetResponseArgument) (*GetResponse, error) {
	ctx, span := s.tracer.Start(ctx, "federation.GetResponse")
	defer span.End()
	ctx = grpcfed.WithLogger(ctx, grpcfed.Logger(ctx), grpcfed.LogAttrs(ctx)...)

	grpcfed.Logger(ctx).DebugContext(ctx, "resolve federation.GetResponse", slog.Any("message_args", s.logvalue_Federation_GetResponseArgument(req)))
	type localValueType struct {
		*grpcfed.LocalValue
		vars struct {
			P *Post
		}
	}
	value := &localValueType{LocalValue: grpcfed.NewLocalValue(ctx, s.celEnvOpts, "grpc.federation.private.federation.GetResponseArgument", req)}
	/*
		def {
		  name: "p"
		  message {
		    name: "Post"
		  }
		}
	*/
	def_p := func(ctx context.Context) error {
		return grpcfed.EvalDef(ctx, value, grpcfed.Def[*Post, *localValueType]{
			Name: `p`,
			Type: grpcfed.CELObjectType("federation.Post"),
			Setter: func(value *localValueType, v *Post) error {
				value.vars.P = v
				return nil
			},
			Message: func(ctx context.Context, value *localValueType) (any, error) {
				args := &OtherService_Federation_PostArgument{}
				ret, err := s.resolve_Federation_Post(ctx, args)
				if err != nil {
					return nil, err
				}
				return ret, nil
			},
		})
	}

	if err := def_p(ctx); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}

	// assign named parameters to message arguments to pass to the custom resolver.
	req.OtherService_Federation_GetResponseVariable.P = value.vars.P

	// create a message value to be returned.
	ret := &GetResponse{}

	// field binding section.
	{
		// (grpc.federation.field).custom_resolver = true
		ctx = grpcfed.WithLogger(ctx, grpcfed.Logger(ctx)) // create a new reference to logger.
		var err error
		ret.Post, err = s.resolver.Resolve_Federation_GetResponse_Post(ctx, &OtherService_Federation_GetResponse_PostArgument{
			OtherService_Federation_GetResponseArgument: req,
		})
		if err != nil {
			grpcfed.RecordErrorToSpan(ctx, err)
			return nil, err
		}
	}

	grpcfed.Logger(ctx).DebugContext(ctx, "resolved federation.GetResponse", slog.Any("federation.GetResponse", s.logvalue_Federation_GetResponse(ret)))
	return ret, nil
}

// resolve_Federation_Post resolve "federation.Post" message.
func (s *OtherService) resolve_Federation_Post(ctx context.Context, req *OtherService_Federation_PostArgument) (*Post, error) {
	ctx, span := s.tracer.Start(ctx, "federation.Post")
	defer span.End()
	ctx = grpcfed.WithLogger(ctx, grpcfed.Logger(ctx), grpcfed.LogAttrs(ctx)...)

	grpcfed.Logger(ctx).DebugContext(ctx, "resolve federation.Post", slog.Any("message_args", s.logvalue_Federation_PostArgument(req)))
	type localValueType struct {
		*grpcfed.LocalValue
		vars struct {
			Cmp           bool
			FavoriteValue favorite.FavoriteType
			Reaction      *Reaction
			U             *User
		}
	}
	value := &localValueType{LocalValue: grpcfed.NewLocalValue(ctx, s.celEnvOpts, "grpc.federation.private.federation.PostArgument", req)}
	/*
		def {
		  name: "u"
		  message {
		    name: "User"
		    args: [
		      { name: "id", by: "'foo'" },
		      { name: "name", by: "'bar'" }
		    ]
		  }
		}
	*/
	def_u := func(ctx context.Context) error {
		return grpcfed.EvalDef(ctx, value, grpcfed.Def[*User, *localValueType]{
			Name: `u`,
			Type: grpcfed.CELObjectType("federation.User"),
			Setter: func(value *localValueType, v *User) error {
				value.vars.U = v
				return nil
			},
			Message: func(ctx context.Context, value *localValueType) (any, error) {
				args := &OtherService_Federation_UserArgument{}
				// { name: "id", by: "'foo'" }
				if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
					Value:      value,
					Expr:       `'foo'`,
					CacheIndex: 1,
					Setter: func(v string) error {
						args.Id = v
						return nil
					},
				}); err != nil {
					return nil, err
				}
				// { name: "name", by: "'bar'" }
				if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
					Value:      value,
					Expr:       `'bar'`,
					CacheIndex: 2,
					Setter: func(v string) error {
						args.Name = v
						return nil
					},
				}); err != nil {
					return nil, err
				}
				ret, err := s.resolve_Federation_User(ctx, args)
				if err != nil {
					return nil, err
				}
				return ret, nil
			},
		})
	}

	/*
		def {
		  name: "favorite_value"
		  by: "favorite.FavoriteType.value('TYPE1')"
		}
	*/
	def_favorite_value := func(ctx context.Context) error {
		return grpcfed.EvalDef(ctx, value, grpcfed.Def[favorite.FavoriteType, *localValueType]{
			Name: `favorite_value`,
			Type: grpcfed.CELIntType,
			Setter: func(value *localValueType, v favorite.FavoriteType) error {
				value.vars.FavoriteValue = v
				return nil
			},
			By:           `favorite.FavoriteType.value('TYPE1')`,
			ByCacheIndex: 3,
		})
	}

	/*
		def {
		  name: "cmp"
		  by: "favorite_value == favorite.FavoriteType.TYPE1"
		}
	*/
	def_cmp := func(ctx context.Context) error {
		return grpcfed.EvalDef(ctx, value, grpcfed.Def[bool, *localValueType]{
			Name: `cmp`,
			Type: grpcfed.CELBoolType,
			Setter: func(value *localValueType, v bool) error {
				value.vars.Cmp = v
				return nil
			},
			By:           `favorite_value == favorite.FavoriteType.TYPE1`,
			ByCacheIndex: 4,
		})
	}

	/*
		def {
		  name: "reaction"
		  message {
		    name: "Reaction"
		    args { name: "v", by: "favorite_value" }
		  }
		}
	*/
	def_reaction := func(ctx context.Context) error {
		return grpcfed.EvalDef(ctx, value, grpcfed.Def[*Reaction, *localValueType]{
			Name: `reaction`,
			Type: grpcfed.CELObjectType("federation.Reaction"),
			Setter: func(value *localValueType, v *Reaction) error {
				value.vars.Reaction = v
				return nil
			},
			Message: func(ctx context.Context, value *localValueType) (any, error) {
				args := &OtherService_Federation_ReactionArgument{}
				// { name: "v", by: "favorite_value" }
				if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[favorite.FavoriteType]{
					Value:      value,
					Expr:       `favorite_value`,
					CacheIndex: 5,
					Setter: func(v favorite.FavoriteType) error {
						args.V = v
						return nil
					},
				}); err != nil {
					return nil, err
				}
				ret, err := s.resolve_Federation_Reaction(ctx, args)
				if err != nil {
					return nil, err
				}
				return ret, nil
			},
		})
	}

	// A tree view of message dependencies is shown below.
	/*
	   favorite_value ─┐
	                        cmp ─┐
	   favorite_value ─┐         │
	                   reaction ─┤
	                          u ─┤
	*/
	eg, ctx1 := grpcfed.ErrorGroupWithContext(ctx)

	grpcfed.GoWithRecover(eg, func() (any, error) {
		if err := def_favorite_value(ctx1); err != nil {
			grpcfed.RecordErrorToSpan(ctx1, err)
			return nil, err
		}
		if err := def_cmp(ctx1); err != nil {
			grpcfed.RecordErrorToSpan(ctx1, err)
			return nil, err
		}
		return nil, nil
	})

	grpcfed.GoWithRecover(eg, func() (any, error) {
		if err := def_favorite_value(ctx1); err != nil {
			grpcfed.RecordErrorToSpan(ctx1, err)
			return nil, err
		}
		if err := def_reaction(ctx1); err != nil {
			grpcfed.RecordErrorToSpan(ctx1, err)
			return nil, err
		}
		return nil, nil
	})

	grpcfed.GoWithRecover(eg, func() (any, error) {
		if err := def_u(ctx1); err != nil {
			grpcfed.RecordErrorToSpan(ctx1, err)
			return nil, err
		}
		return nil, nil
	})

	if err := eg.Wait(); err != nil {
		return nil, err
	}

	// assign named parameters to message arguments to pass to the custom resolver.
	req.OtherService_Federation_PostVariable.Cmp = value.vars.Cmp
	req.OtherService_Federation_PostVariable.FavoriteValue = value.vars.FavoriteValue
	req.OtherService_Federation_PostVariable.Reaction = value.vars.Reaction
	req.OtherService_Federation_PostVariable.U = value.vars.U

	// create a message value to be returned.
	ret := &Post{}

	// field binding section.
	// (grpc.federation.field).by = "'post-id'"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
		Value:      value,
		Expr:       `'post-id'`,
		CacheIndex: 6,
		Setter: func(v string) error {
			ret.Id = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "'title'"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
		Value:      value,
		Expr:       `'title'`,
		CacheIndex: 7,
		Setter: func(v string) error {
			ret.Title = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "'content'"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
		Value:      value,
		Expr:       `'content'`,
		CacheIndex: 8,
		Setter: func(v string) error {
			ret.Content = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "u"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[*User]{
		Value:      value,
		Expr:       `u`,
		CacheIndex: 9,
		Setter: func(v *User) error {
			ret.User = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "reaction"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[*Reaction]{
		Value:      value,
		Expr:       `reaction`,
		CacheIndex: 10,
		Setter: func(v *Reaction) error {
			ret.Reaction = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "favorite_value"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[favorite.FavoriteType]{
		Value:      value,
		Expr:       `favorite_value`,
		CacheIndex: 11,
		Setter: func(v favorite.FavoriteType) error {
			favoriteValueValue, err := s.cast_Favorite_FavoriteType__to__Federation_MyFavoriteType(v)
			if err != nil {
				return err
			}
			ret.FavoriteValue = favoriteValueValue
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "cmp"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[bool]{
		Value:      value,
		Expr:       `cmp`,
		CacheIndex: 12,
		Setter: func(v bool) error {
			ret.Cmp = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}

	grpcfed.Logger(ctx).DebugContext(ctx, "resolved federation.Post", slog.Any("federation.Post", s.logvalue_Federation_Post(ret)))
	return ret, nil
}

// resolve_Federation_Reaction resolve "federation.Reaction" message.
func (s *OtherService) resolve_Federation_Reaction(ctx context.Context, req *OtherService_Federation_ReactionArgument) (*Reaction, error) {
	ctx, span := s.tracer.Start(ctx, "federation.Reaction")
	defer span.End()
	ctx = grpcfed.WithLogger(ctx, grpcfed.Logger(ctx), grpcfed.LogAttrs(ctx)...)

	grpcfed.Logger(ctx).DebugContext(ctx, "resolve federation.Reaction", slog.Any("message_args", s.logvalue_Federation_ReactionArgument(req)))
	type localValueType struct {
		*grpcfed.LocalValue
		vars struct {
			Cmp bool
		}
	}
	value := &localValueType{LocalValue: grpcfed.NewLocalValue(ctx, s.celEnvOpts, "grpc.federation.private.federation.ReactionArgument", req)}
	/*
		def {
		  name: "cmp"
		  by: "$.v == favorite.FavoriteType.TYPE1"
		}
	*/
	def_cmp := func(ctx context.Context) error {
		return grpcfed.EvalDef(ctx, value, grpcfed.Def[bool, *localValueType]{
			Name: `cmp`,
			Type: grpcfed.CELBoolType,
			Setter: func(value *localValueType, v bool) error {
				value.vars.Cmp = v
				return nil
			},
			By:           `$.v == favorite.FavoriteType.TYPE1`,
			ByCacheIndex: 13,
		})
	}

	if err := def_cmp(ctx); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}

	// assign named parameters to message arguments to pass to the custom resolver.
	req.OtherService_Federation_ReactionVariable.Cmp = value.vars.Cmp

	// create a message value to be returned.
	ret := &Reaction{}

	// field binding section.
	// (grpc.federation.field).by = "favorite.FavoriteType.value('TYPE1')"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[favorite.FavoriteType]{
		Value:      value,
		Expr:       `favorite.FavoriteType.value('TYPE1')`,
		CacheIndex: 14,
		Setter: func(v favorite.FavoriteType) error {
			ret.FavoriteType = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "favorite.FavoriteType.name(favorite.FavoriteType.value('TYPE1'))"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
		Value:      value,
		Expr:       `favorite.FavoriteType.name(favorite.FavoriteType.value('TYPE1'))`,
		CacheIndex: 15,
		Setter: func(v string) error {
			ret.FavoriteTypeStr = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "cmp"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[bool]{
		Value:      value,
		Expr:       `cmp`,
		CacheIndex: 16,
		Setter: func(v bool) error {
			ret.Cmp = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}

	grpcfed.Logger(ctx).DebugContext(ctx, "resolved federation.Reaction", slog.Any("federation.Reaction", s.logvalue_Federation_Reaction(ret)))
	return ret, nil
}

// resolve_Federation_User resolve "federation.User" message.
func (s *OtherService) resolve_Federation_User(ctx context.Context, req *OtherService_Federation_UserArgument) (*User, error) {
	ctx, span := s.tracer.Start(ctx, "federation.User")
	defer span.End()
	ctx = grpcfed.WithLogger(ctx, grpcfed.Logger(ctx), grpcfed.LogAttrs(ctx)...)

	grpcfed.Logger(ctx).DebugContext(ctx, "resolve federation.User", slog.Any("message_args", s.logvalue_Federation_UserArgument(req)))
	type localValueType struct {
		*grpcfed.LocalValue
		vars struct {
		}
	}
	value := &localValueType{LocalValue: grpcfed.NewLocalValue(ctx, s.celEnvOpts, "grpc.federation.private.federation.UserArgument", req)}

	// create a message value to be returned.
	ret := &User{}

	// field binding section.
	// (grpc.federation.field).by = "$.id"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
		Value:      value,
		Expr:       `$.id`,
		CacheIndex: 17,
		Setter: func(v string) error {
			ret.Id = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}
	// (grpc.federation.field).by = "$.name"
	if err := grpcfed.SetCELValue(ctx, &grpcfed.SetCELValueParam[string]{
		Value:      value,
		Expr:       `$.name`,
		CacheIndex: 18,
		Setter: func(v string) error {
			ret.Name = v
			return nil
		},
	}); err != nil {
		grpcfed.RecordErrorToSpan(ctx, err)
		return nil, err
	}

	grpcfed.Logger(ctx).DebugContext(ctx, "resolved federation.User", slog.Any("federation.User", s.logvalue_Federation_User(ret)))
	return ret, nil
}

// cast_Favorite_FavoriteType__to__Federation_MyFavoriteType cast from "favorite.FavoriteType" to "federation.MyFavoriteType".
func (s *OtherService) cast_Favorite_FavoriteType__to__Federation_MyFavoriteType(from favorite.FavoriteType) (MyFavoriteType, error) {
	var ret MyFavoriteType
	switch from {
	case favorite.FavoriteType_UNKNOWN:
		ret = MyFavoriteType_UNKNOWN
	case favorite.FavoriteType_TYPE1:
		ret = MyFavoriteType_TYPE1
	default:
		ret = 0
	}
	return ret, nil
}

func (s *OtherService) logvalue_Favorite_FavoriteType(v favorite.FavoriteType) slog.Value {
	switch v {
	case favorite.FavoriteType_UNKNOWN:
		return slog.StringValue("UNKNOWN")
	case favorite.FavoriteType_TYPE1:
		return slog.StringValue("TYPE1")
	case favorite.FavoriteType_TYPE2:
		return slog.StringValue("TYPE2")
	}
	return slog.StringValue("")
}

func (s *OtherService) logvalue_Federation_GetResponse(v *GetResponse) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.Any("post", s.logvalue_Federation_Post(v.GetPost())),
	)
}

func (s *OtherService) logvalue_Federation_GetResponseArgument(v *OtherService_Federation_GetResponseArgument) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.String("id", v.Id),
	)
}

func (s *OtherService) logvalue_Federation_MyFavoriteType(v MyFavoriteType) slog.Value {
	switch v {
	case MyFavoriteType_UNKNOWN:
		return slog.StringValue("UNKNOWN")
	case MyFavoriteType_TYPE1:
		return slog.StringValue("TYPE1")
	}
	return slog.StringValue("")
}

func (s *OtherService) logvalue_Federation_Post(v *Post) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.String("id", v.GetId()),
		slog.String("title", v.GetTitle()),
		slog.String("content", v.GetContent()),
		slog.Any("user", s.logvalue_Federation_User(v.GetUser())),
		slog.Any("reaction", s.logvalue_Federation_Reaction(v.GetReaction())),
		slog.String("favorite_value", s.logvalue_Federation_MyFavoriteType(v.GetFavoriteValue()).String()),
		slog.Bool("cmp", v.GetCmp()),
	)
}

func (s *OtherService) logvalue_Federation_PostArgument(v *OtherService_Federation_PostArgument) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue()
}

func (s *OtherService) logvalue_Federation_Reaction(v *Reaction) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.String("favorite_type", s.logvalue_Favorite_FavoriteType(v.GetFavoriteType()).String()),
		slog.String("favorite_type_str", v.GetFavoriteTypeStr()),
		slog.Bool("cmp", v.GetCmp()),
	)
}

func (s *OtherService) logvalue_Federation_ReactionArgument(v *OtherService_Federation_ReactionArgument) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.String("v", s.logvalue_Favorite_FavoriteType(v.V).String()),
	)
}

func (s *OtherService) logvalue_Federation_User(v *User) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.String("id", v.GetId()),
		slog.String("name", v.GetName()),
	)
}

func (s *OtherService) logvalue_Federation_UserArgument(v *OtherService_Federation_UserArgument) slog.Value {
	if v == nil {
		return slog.GroupValue()
	}
	return slog.GroupValue(
		slog.String("id", v.Id),
		slog.String("name", v.Name),
	)
}
