// Code generated by protoc-gen-grpc-federation. DO NOT EDIT!
// versions:
//
//	protoc-gen-grpc-federation: dev
//
// source: federation/other.proto
package federation

import (
	"reflect"
)

var (
	_ = reflect.Invalid // to avoid "imported and not used error"
)

// Federation_V2Dev_RefArgument is argument for "federation.v2dev.Ref" message.
type Federation_V2Dev_RefArgument struct {
}
