// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: grpc/federation/plugin.proto

package federation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginRule define schema of CEL plugin.
type PluginRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Export []*Export `protobuf:"bytes,1,rep,name=export,proto3" json:"export,omitempty"`
}

func (x *PluginRule) Reset() {
	*x = PluginRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRule) ProtoMessage() {}

func (x *PluginRule) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRule.ProtoReflect.Descriptor instead.
func (*PluginRule) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginRule) GetExport() []*Export {
	if x != nil {
		return x.Export
	}
	return nil
}

// Export describe the schema to be exposed as a CEL plugin.
type Export struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the plugin name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// desc is the description of plugin.
	// This description is used as documentation at code generation.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// types describe the message type you want to expose.
	Types []*ReceiverType `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	// functions describe the definition of the function you want to expose.
	Functions []*CELFunction `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
	// variables describe the definition of the variable you want to expose.
	Variables []*CELVariable `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
}

func (x *Export) Reset() {
	*x = Export{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Export) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Export) ProtoMessage() {}

func (x *Export) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Export.ProtoReflect.Descriptor instead.
func (*Export) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Export) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Export) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Export) GetTypes() []*ReceiverType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Export) GetFunctions() []*CELFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Export) GetVariables() []*CELVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

// CELFunction represents the CEL function definition.
type CELFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the function name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// desc is the description of function.
	// This description is used as documentation at code generation.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// args describe the definition of the function argument.
	Args []*CELFunctionArgument `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// return describe the definition of return type of function.
	Return *CELType `protobuf:"bytes,4,opt,name=return,proto3" json:"return,omitempty"`
}

func (x *CELFunction) Reset() {
	*x = CELFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CELFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CELFunction) ProtoMessage() {}

func (x *CELFunction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CELFunction.ProtoReflect.Descriptor instead.
func (*CELFunction) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *CELFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CELFunction) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CELFunction) GetArgs() []*CELFunctionArgument {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CELFunction) GetReturn() *CELType {
	if x != nil {
		return x.Return
	}
	return nil
}

// ReceiverType represents methods tied to the message.
type ReceiverType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the message name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// desc is the description of plugin.
	// This description is used as documentation at code generation.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// methods describe the definition of the method for the message.
	Methods []*CELFunction `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *ReceiverType) Reset() {
	*x = ReceiverType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiverType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverType) ProtoMessage() {}

func (x *ReceiverType) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverType.ProtoReflect.Descriptor instead.
func (*ReceiverType) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiverType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReceiverType) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ReceiverType) GetMethods() []*CELFunction {
	if x != nil {
		return x.Methods
	}
	return nil
}

// CELFunctionArgument represents the function argument.
type CELFunctionArgument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the argument value name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// desc is the description of plugin.
	// This description is used as documentation at code generation.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// type is the argument type.
	// The value must be one that can be referenced on the Protocol Buffers.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// repeated is whether repeated type or not.
	Repeated bool `protobuf:"varint,4,opt,name=repeated,proto3" json:"repeated,omitempty"`
}

func (x *CELFunctionArgument) Reset() {
	*x = CELFunctionArgument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CELFunctionArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CELFunctionArgument) ProtoMessage() {}

func (x *CELFunctionArgument) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CELFunctionArgument.ProtoReflect.Descriptor instead.
func (*CELFunctionArgument) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CELFunctionArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CELFunctionArgument) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CELFunctionArgument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CELFunctionArgument) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

// CELType represents type information.
type CELType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is the type name.
	// The value must be one that can be referenced on the Protocol Buffers.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// desc is the description of plugin.
	// This description is used as documentation at code generation.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// repeated is whether repeated type or not.
	Repeated bool `protobuf:"varint,3,opt,name=repeated,proto3" json:"repeated,omitempty"`
}

func (x *CELType) Reset() {
	*x = CELType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CELType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CELType) ProtoMessage() {}

func (x *CELType) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CELType.ProtoReflect.Descriptor instead.
func (*CELType) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CELType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CELType) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CELType) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

// CELVariable represents CEL variable.
type CELVariable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the variable name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// desc is the description of plugin.
	// This description is used as documentation at code generation.
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// type is the argument type.
	// The value must be one that can be referenced on the Protocol Buffers.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// repeated is whether repeated type or not.
	Repeated bool `protobuf:"varint,4,opt,name=repeated,proto3" json:"repeated,omitempty"`
}

func (x *CELVariable) Reset() {
	*x = CELVariable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_federation_plugin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CELVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CELVariable) ProtoMessage() {}

func (x *CELVariable) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_federation_plugin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CELVariable.ProtoReflect.Descriptor instead.
func (*CELVariable) Descriptor() ([]byte, []int) {
	return file_grpc_federation_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CELVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CELVariable) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CELVariable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CELVariable) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

var file_grpc_federation_plugin_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*PluginRule)(nil),
		Field:         1187,
		Name:          "grpc.federation.plugin",
		Tag:           "bytes,1187,opt,name=plugin",
		Filename:      "grpc/federation/plugin.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional grpc.federation.PluginRule plugin = 1187;
	E_Plugin = &file_grpc_federation_plugin_proto_extTypes[0]
)

var File_grpc_federation_plugin_proto protoreflect.FileDescriptor

var file_grpc_federation_plugin_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3d, 0x0a, 0x0a, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x12,
	0x2f, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0xdd, 0x01, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x45,
	0x4c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x45, 0x4c, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x22, 0xa1, 0x01, 0x0a, 0x0b, 0x43, 0x45, 0x4c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x38, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x65,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x45, 0x4c, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x45, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x72, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x22, 0x6e, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x36, 0x0a, 0x07,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x45, 0x4c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x22, 0x6d, 0x0a, 0x13, 0x43, 0x45, 0x4c, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x4d, 0x0a, 0x07, 0x43, 0x45, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x22, 0x65, 0x0a, 0x0b, 0x43, 0x45, 0x4c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x3a, 0x52, 0x0a, 0x06, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xa3, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x42, 0x3f, 0x5a,
	0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x72, 0x63,
	0x61, 0x72, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x3b, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_federation_plugin_proto_rawDescOnce sync.Once
	file_grpc_federation_plugin_proto_rawDescData = file_grpc_federation_plugin_proto_rawDesc
)

func file_grpc_federation_plugin_proto_rawDescGZIP() []byte {
	file_grpc_federation_plugin_proto_rawDescOnce.Do(func() {
		file_grpc_federation_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_federation_plugin_proto_rawDescData)
	})
	return file_grpc_federation_plugin_proto_rawDescData
}

var file_grpc_federation_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_federation_plugin_proto_goTypes = []interface{}{
	(*PluginRule)(nil),               // 0: grpc.federation.PluginRule
	(*Export)(nil),                   // 1: grpc.federation.Export
	(*CELFunction)(nil),              // 2: grpc.federation.CELFunction
	(*ReceiverType)(nil),             // 3: grpc.federation.ReceiverType
	(*CELFunctionArgument)(nil),      // 4: grpc.federation.CELFunctionArgument
	(*CELType)(nil),                  // 5: grpc.federation.CELType
	(*CELVariable)(nil),              // 6: grpc.federation.CELVariable
	(*descriptorpb.FileOptions)(nil), // 7: google.protobuf.FileOptions
}
var file_grpc_federation_plugin_proto_depIdxs = []int32{
	1, // 0: grpc.federation.PluginRule.export:type_name -> grpc.federation.Export
	3, // 1: grpc.federation.Export.types:type_name -> grpc.federation.ReceiverType
	2, // 2: grpc.federation.Export.functions:type_name -> grpc.federation.CELFunction
	6, // 3: grpc.federation.Export.variables:type_name -> grpc.federation.CELVariable
	4, // 4: grpc.federation.CELFunction.args:type_name -> grpc.federation.CELFunctionArgument
	5, // 5: grpc.federation.CELFunction.return:type_name -> grpc.federation.CELType
	2, // 6: grpc.federation.ReceiverType.methods:type_name -> grpc.federation.CELFunction
	7, // 7: grpc.federation.plugin:extendee -> google.protobuf.FileOptions
	0, // 8: grpc.federation.plugin:type_name -> grpc.federation.PluginRule
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	8, // [8:9] is the sub-list for extension type_name
	7, // [7:8] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_federation_plugin_proto_init() }
func file_grpc_federation_plugin_proto_init() {
	if File_grpc_federation_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_federation_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_federation_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Export); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_federation_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CELFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_federation_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiverType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_federation_plugin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CELFunctionArgument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_federation_plugin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CELType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_federation_plugin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CELVariable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_federation_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_grpc_federation_plugin_proto_goTypes,
		DependencyIndexes: file_grpc_federation_plugin_proto_depIdxs,
		MessageInfos:      file_grpc_federation_plugin_proto_msgTypes,
		ExtensionInfos:    file_grpc_federation_plugin_proto_extTypes,
	}.Build()
	File_grpc_federation_plugin_proto = out.File
	file_grpc_federation_plugin_proto_rawDesc = nil
	file_grpc_federation_plugin_proto_goTypes = nil
	file_grpc_federation_plugin_proto_depIdxs = nil
}
