name: release-vscode
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release-vscode:
    name: release vscode extension
    runs-on: ubuntu-latest
    steps:
      - name: install npx
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y npm nodejs
          sudo npm -g install n
          sudo n stable
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: extract version from tags
        id: meta
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --clean
      - name: build extension
        run: |
          make build/vscode-extension
        env:
          VERSION: ${{ steps.meta.outputs.VERSION }}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./lsp/client/vscode/grpc-federation-*.vsix
            ./dist/grpc-federation_*_checksums.txt
            ./dist/grpc-federation_*_*_*.tar.gz
            ./dist/grpc-federation_*_*_*.zip
      - name: publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: "./lsp/client/vscode/grpc-federation-${{ steps.meta.outputs.VERSION }}.vsix"
